# Generated by Django 6.0.3 on 2026-05-06 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_orderitem_is_scheme_visible'),
        ('users', '0010_remove_schemeproduct_state_schemeproduct_state_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='basic_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='market_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='OrderItemScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_scheme', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='orders.orderitem')),
                ('scheme', models.ForeignKey(blank=True, db_column='scheme_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_schemes', to='users.schemeproduct')),
            ],
            options={
                'db_table': 'order_item_schemes',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('temp_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_instances', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_template',
                'unique_together': {('user', 'order')},
            },
        ),
    ]
