# Generated by Django 6.0.3 on 2026-05-02 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_orderitemscheme'),
        ('orders', '0020_alter_orderitem_basic_price_and_more'),
    ]

    operations = [
    ]
