# Generated by Django 6.0.3 on 2026-05-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_schemeproduct_state_schemeproduct_state_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyproductassignment',
            name='basic_rate',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12),
        ),
    ]
